### ISSUE TITLE
Instant: How to derive asset ID for additionalAssetMetaDataMap?

### ISSUE THREAD

**Issue by joncursi** [0xProject/0x-protocol-specification#14]
I want to add 0x Instant to [Cheddur](https://www.cheddur.com/), and I would like to add more ERC20 tokens than are available in the default list. As an example, let's say Self Storage Coin (https://etherscan.io/token/0xa3ceac0aac5c5d868973e546ce4731ba90e873c2).

I see from the docs that this is done via the `additionalAssetMetaDataMap` configuration option, but the part I do not understand is how to generate asset IDs for use within this mapping.

Consider the following example from the docs:

```js
additionalAssetMetaDataMap: {
         '0xf47261b0000000000000000000000000744d70fdbe2bc4cf95131626614a1764df805b9e': {
                assetProxyId: '0xf47261b0', // ERC20 Proxy Id
                decimals: 18,
                primaryColor: '#F2F7FF', // Optional
                symbol: 'XXX',
                name: 'My Custom Token',
            },
        },
```

How is `0xf47261b0000000000000000000000000744d70fdbe2bc4cf95131626614a1764df805b9e` derived? It looks to be a combination of the ERC20 Proxy Id + padded zeros + the token's contract address. But the questions here are...

* How many zeros and why?
* Does the number of zeros vary from token to token?
* Is there a clean way to generate an asset's ID in javascript given a contract address and proxy type, or should we just use string concatenation?

Thanks!

**Comment by fragosti** [comment]
Hi @joncursi 
Great questions! Yes, assetData can be a bit confusing. We are working to make this clearer in the documentation but in the meantime I hope this answer is sufficient!

From asset data encoding [explanation for SRA spec](https://github.com/0xProject/standard-relayer-api#asset-data-encoding):

As we now support multiple [token transfer proxies](https://github.com/0xProject/0x-protocol-specification/blob/master/v2/v2-specification.md#assetproxy), the identifier of which proxy to use for the token transfer must be encoded, along with the token information. Each proxy in 0x v2 has a unique identifier. If you're using 0x.js there will be helper methods for this [encoding](https://0xproject.com/docs/0x.js#assetDataUtils-encodeAssetProxyId) and [decoding](https://0xproject.com/docs/0x.js#assetDataUtils-decodeAssetProxyId).

The identifier for the Proxy uses a similar scheme to [ABI function selectors](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI#function-selector).

```
// ERC20 Proxy ID  0xf47261b0
bytes4(keccak256("ERC20Token(address)"))
// ERC721 Proxy ID 0x02571792
bytes4(keccak256("ERC721Token(address,uint256)"))
```

Asset data is encoded using [ABI encoding](https://solidity.readthedocs.io/en/develop/abi-spec.html).

For example, encoding the ERC20 token contract (address: 0x1dc4c1cefef38a777b15aa20260a54e584b16c48) using the ERC20 Transfer Proxy (id: 0xf47261b0) would be:

```
0xf47261b00000000000000000000000001dc4c1cefef38a777b15aa20260a54e584b16c48
```

Encoding the ERC721 token contract (address: `0x371b13d97f4bf77d724e78c16b7dc74099f40e84`), token id (id: `99`, which hex encoded is `0x63`) and the ERC721 Transfer Proxy (id: `0x02571792`) would be:

```
0x02571792000000000000000000000000371b13d97f4bf77d724e78c16b7dc74099f40e840000000000000000000000000000000000000000000000000000000000000063
```

For more information see [the Asset Proxy](https://github.com/0xProject/0x-protocol-specification/blob/master/v2/v2-specification.md#erc20proxy) section of the v2 spec and the [Ethereum ABI Spec](https://solidity.readthedocs.io/en/develop/abi-spec.html).

To answer your questions individually:
#### How many zeros and why?
There are always 24 zeros after `0xf47261b0` unless your contract address starts with a 0 because that is how the encoding works for ERC20. 

#### Does the number of zeros vary from token to token?
It varies between token standards, but remains the same for ERC20. 

#### Is there a clean way to generate an asset's ID in javascript given a contract address and proxy type, or should we just use string concatenation?

Yes. [encoding](https://0xproject.com/docs/0x.js#assetDataUtils-encodeAssetProxyId) and [decoding](https://0xproject.com/docs/0x.js#assetDataUtils-decodeAssetProxyId).

**Comment by joncursi** [comment]
Exactly what I was looking for - thank you!

Is it okay to run 0x.js utilities in the browser? I don’t wanna bloat the
bundle too much.

**Comment by fragosti** [comment]
0x.js is just re-exporting the contents from `@0x/order-utils` (and other packages).
```
import { assetDataUtils } from '@0x/order-utils';
```

**Comment by joncursi** [comment]
Thanks @fragosti - that's exactly the import I was looking for!

Our 0x Instant integration is now live on Cheddur for all of the tokens supported by Radar. You can check it out on [ZRX](https://www.cheddur.com/coins/0x) (see the "Buy Now with Ethereum" button).

Couple follow-up points:

1. What is the process for new tokens being added to 0x? Is this community-driven at the 0x level, or more in the hands of Radar and the other relayers? Curious what the pipeline looks like from a business perspective so that we can project our volume.
2. I'd like to invite you to [claim the ZRX profile](https://www.cheddur.com/manage?profileType=COIN&slug=0x) on Cheddur. It's free and is designed to help you interact with your 200+ followers and grow your community. :)

Thanks man!
