### ISSUE TITLE
Cancellation Spec vs Contract

### ISSUE THREAD

**Issue by AusIV** [0xProject/0x-protocol-specification#5]
For orderEpoch, the spec says:

> Orders specified makerAddress and senderAddress with a salt <= this value are considered cancelled.

Yet in the contract has the code:

    orderEpoch[order.makerAddress][order.senderAddress] > order.salt

which is equivalent to "salt < this value" rather than "salt <= this value".

See: https://github.com/0xProject/0x-monorepo/blob/v2-prototype/packages/contracts/src/2.0.0/protocol/Exchange/MixinExchangeCore.sol#L187

**Comment by AusIV** [comment]
To add to this, the value emitted by the event is the value submitted by the user + 1.

So for the cancelOrdersUpTo call, it would be accurate to say 

> Orders specified makerAddress and senderAddress with a salt **<=** this value are considered cancelled

but since the event emits (this value) + 1, the event should read

> Orders specified makerAddress and senderAddress with a salt **<** this value are considered cancelled

As a side note, expect some confusion around the fact that the event emits the user submitted value + 1. If the spec can't even keep it straight, users don't stand much of a chance.

**Comment by abandeali1** [comment]
This has been fixed in the spec (comments still need to be fixed in the contracts). 

Agreed that the fact that the event emits the user value + 1 is a bit confusing. We chose to do it this way because we wanted the user to be able to call `cancelOrdersUpTo` with an input of X to cancel all orders with a salt <= X, so we add one to the input on behalf of the user. 

Why couldn't we use
